import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import '@styles/globals.css';
import BasketContextProvider from '@context/Basket';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BasketContextProvider>{children}</BasketContextProvider>
      </body>
    </html>
  );
}
